### DEFAULT
# language  = "en"   # Search for manga in a specified language. (https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes)
# outdir    = "."    # Output directory for downloading chapters. Use "/" slash.
# download  = false  # Download range (see Readme). [ "all" | <range> | false ]
# archive   = false  # How to archive manga in file. [ "manga" | "volume" | "chapter" | false ]
# ext       = "zip"  # Archive format/extension. [ "zip" | "cbz" | "pdf" ]
# keep      = false  # Don't delete original images after archiving. [ true | false ]
# datasaver = false  # Download images in lower quality. [ true | false ]
# resolve   = "one"  # How to display duplicate chapters. [ "all" | "one" | "manual" ]
# gui       = true   # Runs a program in GUI mode. [ true | false ]
# proxy     = false  # HTTP/S proxy. [ "user:pass@host:port" | false ]
# socks     = false  # Socks5 proxy. [ "user:pass@host:port" | false ]

language  = "en"
outdir    = "."
download  = false
archive   = false
ext       = "zip"
keep      = false
datasaver = false
resolve   = "all"
gui       = true

proxy = false
socks = false